### PR TITLE
Jump directly to files from repo status buffer

### PR DESCRIPTION
**Pull request by snogge**

### CODE REVIEW

**Comment by canatella** [comment]
Hello,

Thanks for your contribution. Could you update the tests in `test/repo-test.el` and `test/repo-functional-test.el` to check the new behaviour of `repo-find` and check that they pass using `cask exec ert-runner` ? 

Thank you!

**Comment by snogge** [comment]
Sure, I'll take allok at the tests.  I just missed they were there.

**Comment by snogge** [comment]
Writing test exposed a serious bug, so I did a rewrite.

**Comment by canatella** [comment]
Merged, thank you!

**Pull request merged**
